---
title: "About Me"
---

I am a young, white, queer, & disabled woman living in Chicago and Baltimore. I grew up in Indiana, where I lived until  moving to Manhattan for graduate school. I study public health in the criminal legal system. I also assist in organizing for the abolition of the prison industrial complex, work as a birth doula, and am a sexual health & relationship counselor. 

# Education

## Columbia University
I am currently in the second year of the Columbia University Mailman School of Public Health Master in Public Health program. My degree will be in Population & Family Health with a Certificate in Health & Human Rights. I am mentored by Professor Joanne Csete and Dr. Pia Mauro. I will graduate in May of 2021 and am a Merit Scholar. 

## Purdue University
I graduate from Purdue University in West Lafayette, IN in May of 2015 with a Bachelor of Science in Human Developmental & Family Science, a Bachelor of Arts in Political Science, a certificate in Human Rights, and the Honors College diploma, with a 4.0 GPA. I am grateful to be a Stamps Scholar and a member of Phi Beta Kappa. During my time at Purdue, I conducted research on supporting parents of children in the child welfare system, sexual & reproductive health among adolescents in foster care, and the dehumanization of immmigrants and refugees. I was mentored by Dr. Jay McCann, Dr. Sharon Christ, and Brittany Mihalec-Adkins. 

## Languages
I am proficient in American Sign Language and am working on learning Spanish. 

## Skills
SPSS, R, STATA, Tableau, Qualtrics, Dedoose, qualitative data analysis, quantitative data analysis, data entry & cleaning, data visualization, policy analysis, literature reviews, academic writing, public speaking, verbal & written communication, teamwork, critical thinking, and independent work.

