---
title: "NYC Restaurant Inspection Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: flatly
    code_folding: hide
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(rvest)
library(httr)

library(plotly)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

data(rest_inspec)

rest_inspec =
  rest_inspec %>% 
  filter(grade %in% c("A", "B", "C"), boro != "Missing") %>% 
  mutate(boro = str_to_title(boro))

rmarkdown::render("dashboard_template.Rmd", output_format = "flexdashboard::flex_dashboard")

```

Column {data-width=650}
-----------------------------------------------------------------------

### Manhattan Scores over Time

```{r echo=FALSE}
rest_inspec %>%
  filter(boro == "Manhattan") %>% 
plot_ly(x = ~inspection_date, y = ~score, color = ~grade, type = "scatter", mode = "markers", colors = "viridis") %>% 
  add_trace(opacity = 0.5, showlegend = F) 
```

Column {data-width=350}
-----------------------------------------------------------------------

### Count of Grades in Boroughs

```{r echo=FALSE}
rest_inspec %>% 
  group_by(boro, grade) %>% 
  summarize(n = n()) %>% 
  plot_ly(x = ~grade, y = ~n, color = ~boro, colors = "viridis") 
```

### Score Distribution per Borough

```{r echo=FALSE}
rest_inspec %>% 
  filter(boro != "Missing") %>% 
  mutate(boro = str_to_title(boro)) %>% 
  plot_ly(x = ~boro, y = ~score, type = "box", color = ~boro, colors = "viridis")
```

